### ISSUE TITLE
draw.lua is missing

### ISSUE THREAD

**Issue by deutzfahraustria** [webalizer-gt/ProSeed17#1]
Error: Can't load resource 'C:/Users/******/Documents/My Games/FarmingSimulator2017/mods/ZZZ_sowingSupp/draw.lua'

**Comment by webalizer-gt** [comment]
Not for public use yet! Missing file is on purpose!

**Comment by zed636** [comment]
Hi, I have this error:
Error: Can't load resource 'C:/Users/******/Documents/My Games/FarmingSimulator2017/mods/FS17_ProSeed/draw.lua'
...is the mod pulic now?

**Comment by gotchTOM** [comment]
Hi,

it isn´t public yet... you will find it on the ModHub, the official Farming-Simulator website.
