### ISSUE TITLE
Logfehler

### ISSUE THREAD

**Issue by kleinefarm** [webalizer-gt/ProSeed17#13]
Hallo,
ich habe proSeed herunter geladen und als FS17_ProSeed.zip korrekt gepackt in den Modordner gelegt.
Zudem habe ich https://www.modhoster.de/mods/gps--2 davon die aktuellste Version hgerunter geladen.

Nutzen kann man die funktionen in Sähmaschinen nicht,   zudem wird das ShemaOverlay komplett ausgelendet,   sobald man auf die Drille wechselt.

Logfehler gibt es folgende:
`Error: Can't load resource 'C:/Users/Lars/Documents/My Games/FarmingSimulator2017/mods/FS17_ProSeed/draw.lua'.`
`Error: Running LUA method 'draw'.
dataS/scripts/vehicles/Vehicle.lua:0: attempt to call field 'draw' (a nil value)
Error: Running LUA method 'draw'.
dataS/scripts/vehicles/Vehicle.lua:0: attempt to call field 'draw' (a nil value)
Error: Running LUA method 'draw'.`
[log.txt](https://github.com/webalizer-gt/ProSeed17/files/671921/log.txt)

**Comment by kleinefarm** [comment]
https://github.com/webalizer-gt/ProSeed17/issues/1

Frage somit wohl beantwortet.

**Comment by webalizer-gt** [comment]
Habt noch ein klein wenig Geduld. Es ist bald soweit ;-)

**Comment by holse1965** [comment]
Ich warte gespannt mit Geduld. Wird es so gut sein wie in ls 15 oder besser. So ist es das Warten wert.

Im Voraus vielen Dank für einen fantastischen mod

Palle Schilling (Holse) nordicmods.org

**Comment by webalizer-gt** [comment]
Released:
http://farming-simulator.com/mod.php?lang=de&country=de&mod_id=64561&title=fs2017
