### ISSUE TITLE
ProSeed nicht kompatibel mit Fronttank des Kuhn DLCs

### ISSUE THREAD

**Issue by skeletonwburg** [webalizer-gt/ProSeed17#23]
Ich wollte eben die Drillkombi vom neuen DLC testen, als mir auffiel, dass beim Kauf des Fronttanks das Spiel abschmiert. 
Es wird der Fehler `Error: Running LUA method 'update'.
G:/Dokumente/My Games/FarmingSimulator2017/mods/FS17_ProSeed/DrivingLine/drivingLine.lua:44: bad argument #1 to 'sub' (string expected, got nil)` ausgegeben. 

Anscheinend müsstet ihr eine Funktion einbauen, die Fronttanks ohne AI Marker/workArea ausschließt bzw. nicht als Sähmaschine für DrivingLine behandelt, sondern eben nur als Saattanks. Das ist allerdings nur eine Vermutung und ihr werdet sicher einen Weg finden, wie man da die Kompatibilität wiederherstellen kann ^^.
[log.txt](https://github.com/webalizer-gt/ProSeed17/files/772682/log.txt)

**Comment by gotchTOM** [comment]
Richtig vermutet ;)

Lösung muss nun noch getestet werden.

Danke, skeletonwburg
