### ISSUE TITLE
Fehler

### ISSUE THREAD

**Issue by Paul2510** [webalizer-gt/ProSeed17#25]
Hi hab die aktuelle version geladen und bekomm folgenden Fehler 
Error: Running LUA method 'draw'.
dataS/scripts/vehicles/Vehicle.lua(2736) : attempt to call field 'draw' (a nil value)
Sobald ich die Orginal  SääMaschiene anhänge verschwindet das Menü!

LG
[log.txt](https://github.com/webalizer-gt/ProSeed17/files/792167/log.txt)

**Comment by webalizer-gt** [comment]
Der Code vom github ist auch weiterhin nicht alleine lauffähig. Das Update wird demnächst im Modhub erscheinen.

**Comment by Paul2510** [comment]
Ok danke mein Fehler!
