### ISSUE TITLE
Spurreisser

### ISSUE THREAD

**Issue by gotchTOM** [webalizer-gt/ProSeed17#4]
Tastenkombi links Shift + y für den rechten Spurreisser:
Wenn man die Shift-Taste vor der y-Taste losläßt, fährt der Spurreisser wieder ein...
Wollen wir daran noch etwas ändern, oder sollen die Spieler einfach aufpassen?
Die Tastenkombi kann ja auch jeder für sich auf eine einzelne Taste legen.

Könntest du im HUD noch eine Anzeige für die Spurreisser basteln, damit man sieht welcher aktiv ist ohne nach hinten schauen zu müssen?

**Comment by gotchTOM** [comment]
Habs nochmal erweitert:

Jeder Spuranreisser hat jetzt seine eigene Taste, die im Menü frei belegt werden kann.
Der Linke hatte ja die Standard-Taste (Gerätefunktion 4), die bei einem Tastenwechsel sonst anders belegt werden müßte.

Wenn man beiden Spuranreissern die gleiche Taste zuweist, verhält sich das Ganze wie in Realität mit einem Steuergerät:
-links klappt aus
-links klappt ein
-rechts klappt aus
-rechts klappt ein 
-und von vorne

**Comment by webalizer-gt** [comment]
Wow. Wir kriegens tatsächlich zeitgleich hin... ;-)
Aber ich habe an anderer Stelle gebastelt.
