### ISSUE TITLE
Einstellen des Abstandes nicht möglich

### ISSUE THREAD

**Issue by Aramet01** [webalizer-gt/ProSeed17#41]
Ich wollte schauen wie weit der Abstand im Proseed eingestellet werden kann und kam auf 72m mit der 
YP-2425A da ich jetzt aber auf 36m einstellen möchte musste ich feststellen das das nict möglich ist! hat jemand eine Idee wieso ?

**Comment by webalizer-gt** [comment]
Das ist ein Fehler im Script, den wir beheben werden. Diese Arbeitsbreite war nicht vorgesehen.

Bis dahin bitte entweder die Maschine neu kaufen, oder im Savegame beim Eintrag der Sämaschine den Wert von nSMdrives="4" auf 2 ändern.

**Comment by webalizer-gt** [comment]
Should be fixed: https://github.com/webalizer-gt/ProSeed17/commit/a52b119adce68d87247e9a5aaf09e8e9d21dd2b9
